<a href="https://colab.research.google.com/github/Utkarsha1407/DSBDA-Practical/blob/main/Facebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/dataset_Facebook - dataset_Facebook.csv")

In [ ]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [ ]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [ ]:
df.shape

(500, 19)

In [ ]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

a. Create Data Subsets

In [ ]:
subset_1 = df[['like', 'share']]
print(subset_1)

       like  share
0      79.0   17.0
1     130.0   29.0
2      66.0   14.0
3    1572.0  147.0
4     325.0   49.0
..      ...    ...
495    53.0   26.0
496    53.0   22.0
497    93.0   18.0
498    91.0   38.0
499    91.0   28.0

[500 rows x 2 columns]

In [ ]:
subset_2 = df[['comment', 'Type']]
print(subset_2)

     comment    Type
0          4   Photo
1          5  Status
2          0   Photo
3         58   Photo
4         19   Photo
..       ...     ...
495        5   Photo
496        0   Photo
497        4   Photo
498        7   Photo
499        0   Photo

[500 rows x 2 columns]

b. Merge Data

In [ ]:
merged_data = pd.merge(subset_1, subset_2, left_on='like', right_on='comment')

In [ ]:
print(merged_data)

      like  share  comment    Type
0      0.0    0.0        0   Photo
1      0.0    0.0        0   Photo
2      0.0    0.0        0  Status
3      0.0    0.0        0  Status
4      0.0    0.0        0   Photo
...    ...    ...      ...     ...
1462  12.0    2.0       12   Photo
1463  12.0    2.0       12   Photo
1464  12.0    2.0       12   Photo
1465  12.0    2.0       12   Photo
1466  56.0   25.0       56   Photo

[1467 rows x 4 columns]

c. Sort Data

In [ ]:
merged_data.sort_values(by='like', ascending= False)

      like  share  comment    Type
838  146.0   15.0      146   Photo
132  146.0    9.0      146   Photo
892  144.0   29.0      144   Photo
130  144.0   10.0      144   Photo
839   64.0    7.0       64   Photo
..     ...    ...      ...     ...
939    0.0    0.0        0   Photo
938    0.0    0.0        0   Photo
937    0.0    0.0        0   Photo
936    0.0    0.0        0   Photo
944    0.0    0.0        0  Status

[1467 rows x 4 columns]

d. Transposing Data

In [ ]:
merged_data.transpose()

,0,1,2,3,4,5,6,7,8,9,...,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466
like,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,56.0
share,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,25.0
comment,0,0,0,0,0,0,0,0,0,0,...,5,5,12,12,12,12,12,12,12,56
Type,Photo,Photo,Status,Status,Photo,Photo,Photo,Photo,Link,Photo,...,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo

In [ ]:
merged_data.T

,0,1,2,3,4,5,6,7,8,9,...,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466
like,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,56.0
share,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,25.0
comment,0,0,0,0,0,0,0,0,0,0,...,5,5,12,12,12,12,12,12,12,56
Type,Photo,Photo,Status,Status,Photo,Photo,Photo,Photo,Link,Photo,...,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo

e. Shape and Reshape Data

In [ ]:
df.shape

(500, 19)

In [ ]:
df.Type.unique()

array(['Photo', 'Status', 'Link', 'Video'], dtype=object)

In [ ]:
pd.melt(df, id_vars='Type', value_vars='like')

       Type variable   value
0     Photo     like    79.0
1    Status     like   130.0
2     Photo     like    66.0
3     Photo     like  1572.0
4     Photo     like   325.0
..      ...      ...     ...
495   Photo     like    53.0
496   Photo     like    53.0
497   Photo     like    93.0
498   Photo     like    91.0
499   Photo     like    91.0

[500 rows x 3 columns]